testFramework:
  enabled: false

ingress:
  enabled: true
  annotation: 
    nginx.ingress.kubernetes.io/ssl-redirect: false
  ingressClassName: nginx
  hosts:
    - grafana
    

# kubectl get secret --namespace grafana grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo    